import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, ArrowRight, BarChart3, BellRing, BookOpen, Bot, BriefcaseBusiness, Building2, ChevronRight, CircleHelp, ClipboardList, Filter, LayoutDashboard, Menu, Search, ShieldCheck, SlidersHorizontal, UserRound, Users, X } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { FLAG_LABELS, SERVICE_LABELS, STATUS_LABELS, getCustomers, getMetrics, getProviders, getSupabaseSession, isSafetyTeamSession, isSupabaseConfigured, loadData, signIn, signOut, subscribeToAuthChanges, saveStatusOverride, localSignIn, localSignOut, getLocalSession } from './data/model'

const navItems = [
  { id: 'overview', label: 'Overview', icon: LayoutDashboard }, { id: 'reports', label: 'Reports', icon: BellRing },
  { id: 'listings', label: 'Listings', icon: Building2 }, { id: 'bookings', label: 'Bookings', icon: BookOpen },
  { id: 'providers', label: 'Providers', icon: Users }, { id: 'customers', label: 'Customers', icon: Users }, { id: 'analytics', label: 'Analytics', icon: BarChart3 },
]
const formatFlag = (value) => FLAG_LABELS[value] || value?.replaceAll('_', ' ') || 'Unknown issue'
const formatStatus = (value) => STATUS_LABELS[value] || value?.replaceAll('_', ' ') || 'Unknown status'
const formatService = (value) => SERVICE_LABELS[value] || value || 'Uncategorized'
const money = (value) => value == null ? '—' : `$${value.toFixed(2)}`
const plural = (count, word) => `${count} ${word}${count === 1 ? '' : 's'}`

function App() {
  const [activeApp, setActiveApp] = useState('hub'); const [data, setData] = useState(null); const [error, setError] = useState(''); const [view, setView] = useState('overview'); const [session, setSession] = useState(null); const [authReady, setAuthReady] = useState(!isSupabaseConfigured)
  const [selectedReport, setSelectedReport] = useState(null); const [globalSearch, setGlobalSearch] = useState(''); const [reportFilters, setReportFilters] = useState({}); const [mobileNav, setMobileNav] = useState(false)
  const useLocalAuth = !isSupabaseConfigured
  const fetchData = () => { setError(''); loadData().then(setData).catch((loadError) => setError(loadError.message)) }
  useEffect(() => {
    if (useLocalAuth) {
      const localSession = getLocalSession()
      setSession(localSession)
      setAuthReady(true)
      return
    }
    getSupabaseSession().then((currentSession) => { setSession(currentSession); setAuthReady(true) }).catch((authError) => { setError(authError.message); setAuthReady(true) })
    const { data: { subscription } } = subscribeToAuthChanges((nextSession) => { setSession(nextSession); setData(null); setSelectedReport(null) })
    return () => subscription.unsubscribe()
  }, [])
  useEffect(() => { if (authReady && (!useLocalAuth || session)) fetchData() }, [authReady, session])
  const handleSignIn = useLocalAuth ? localSignIn : signIn
  const handleSignOut = useLocalAuth ? localSignOut : signOut
  if (activeApp === 'hub') return <TaskLocalHub onOpenApp={setActiveApp} />
  if (!authReady) return <LoadingState message="Checking your safety team session" />
  if (!session) return <LoginState onSignIn={handleSignIn} error={error} useLocalAuth={useLocalAuth} />
  if (!isSafetyTeamSession(session)) return <AccessDeniedState onSignOut={handleSignOut} />
  if (error) return <ErrorState message={error} retry={fetchData} />
  if (!data) return <LoadingState />
  const metrics = getMetrics(data)
  const openReport = (report) => setSelectedReport(report)
  const goToReports = (filters = {}) => { setView('reports'); setReportFilters(filters); setSelectedReport(null) }
  return <div className="app-shell">
    <Sidebar view={view} setView={setView} mobileNav={mobileNav} closeMobile={() => setMobileNav(false)} onOpenHub={() => setActiveApp('hub')} />
    <div className="main-shell"><header className="topbar"><button className="icon-button mobile-menu" onClick={() => setMobileNav(true)} aria-label="Open navigation"><Menu size={20} /></button><div className="crumb"><span>TaskLocal</span><ChevronRight size={15} /><strong>Trust &amp; Safety</strong></div><div className="topbar-actions"><div className="global-search"><Search size={16} /><input value={globalSearch} onChange={(event) => setGlobalSearch(event.target.value)} placeholder="Search IDs across TaskLocal" aria-label="Search IDs across TaskLocal" /><kbd>/</kbd></div><button className="user-chip user-chip-button" onClick={() => handleSignOut().catch((signOutError) => setError(signOutError.message))}><span className="avatar">TS</span><span className="user-name">Sign out</span></button></div></header>
      <main className="content">{view === 'overview' && <Overview data={data} metrics={metrics} openReport={openReport} goToReports={goToReports} />}{view === 'reports' && <Reports data={data} metrics={metrics} globalSearch={globalSearch} openReport={openReport} initialFilters={reportFilters} />}{view === 'listings' && <Listings data={data} openReport={openReport} />}{view === 'bookings' && <Bookings data={data} openReport={openReport} />}{view === 'providers' && <Providers data={data} />}{view === 'customers' && <Customers data={data} />}{view === 'analytics' && <Analytics data={data} metrics={metrics} />}</main>
    </div>{selectedReport && <ReportDrawer report={selectedReport} onClose={() => setSelectedReport(null)} onStatusChange={(status) => { saveStatusOverride(selectedReport.report_id, status).then(fetchData).catch((saveError) => setError(saveError.message)); setSelectedReport({ ...selectedReport, flag_status: status }) }} />}
  </div>
}

function TaskLocalHub({ onOpenApp }) {
  const apps = [
    { id: 'customer', name: 'Customer', description: 'Bookings, requests, and a clear view of every customer journey.', icon: UserRound, tone: 'blue', status: 'Open app' },
    { id: 'provider', name: 'Provider', description: 'Listings, availability, and the tools providers need to do their best work.', icon: BriefcaseIcon, tone: 'amber', status: 'Connection planned' },
    { id: 'safety', name: 'Trust & Safety', description: 'Investigate reports, understand marketplace patterns, and protect the community.', icon: ShieldCheck, tone: 'teal', status: 'Available now' },
    { id: 'messaging', name: 'Messaging / Chatbot', description: 'Conversation history and request context across the TaskLocal experience.', icon: Bot, tone: 'coral', status: 'Connection planned' },
  ]
  return <main className="hub-shell"><div className="hub-orbit hub-orbit-one" /><div className="hub-orbit hub-orbit-two" /><div className="hub-content"><header className="hub-header"><button className="hub-brand" onClick={() => onOpenApp('hub')} aria-label="TaskLocal home"><span className="brand-mark"><ShieldCheck size={20} /></span><span>tasklocal</span></button><div className="hub-status"><span className="status-dot" />One connected workspace</div></header><section className="hub-intro"><div className="eyebrow">TaskLocal workspace</div><h1>Everything your marketplace team needs, in one place.</h1><p>Choose an application to get started. Your connected tools will share context as each part of TaskLocal comes online.</p></section><section className="app-grid" aria-label="TaskLocal applications">{apps.map(({ id, name, description, icon: Icon, tone, status }) => <button key={id} className={`app-card ${tone} ${id === 'safety' || id === 'customer' ? 'app-card-live' : ''}`} onClick={() => id === 'safety' ? onOpenApp('safety') : id === 'customer' ? window.open('https://tasklocal-home-service-customer-app.vercel.app/login', '_blank', 'noopener,noreferrer') : undefined} disabled={id !== 'safety' && id !== 'customer'}><div className="app-card-top"><span className="app-icon"><Icon size={22} /></span><span className="app-status">{status}</span></div><div className="app-card-copy"><h2>{name}</h2><p>{description}</p></div><span className="app-card-action">{id === 'safety' || id === 'customer' ? <>Open app <ArrowRight size={16} /></> : <>Preparing connection <span className="app-card-dots">...</span></>}</span></button>)}</section><footer className="hub-footer"><span>TaskLocal platform</span><span>Secure workspace · Internal tools</span></footer></div></main>
}

function BriefcaseIcon(props) { return <BriefcaseBusiness {...props} /> }
function Sidebar({ view, setView, mobileNav, closeMobile, onOpenHub }) { return <aside className={`sidebar ${mobileNav ? 'sidebar-open' : ''}`}><button className="brand brand-button" onClick={onOpenHub} aria-label="Return to TaskLocal applications"><span className="brand-mark"><ShieldCheck size={19} /></span><span>tasklocal</span></button><div className="workspace-label">Operations workspace</div><nav>{navItems.map(({ id, label, icon: Icon }) => <button key={id} className={`nav-item ${view === id ? 'active' : ''}`} onClick={() => { setView(id); closeMobile() }}><Icon size={17} /><span>{label}</span>{id === 'reports' && <span className="nav-count">!</span>}</button>)}</nav><div className="sidebar-footer"><div className="status-dot" /><div><strong>All systems normal</strong><small>Data refreshed just now</small></div></div></aside> }
function PageHeader({ eyebrow, title, subtitle, action }) { return <div className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{subtitle && <p>{subtitle}</p>}</div>{action}</div> }
function Overview({ data, metrics, openReport, goToReports }) { const attention = [...data.reports].filter((report) => report.flag_status !== 'resolved').sort((a, b) => a.attention.rank - b.attention.rank).slice(0, 5); const flagData = Object.entries(metrics.byFlag).map(([key, value]) => ({ name: formatFlag(key), value, key })); const statusData = Object.entries(metrics.byStatus).map(([key, value]) => ({ name: formatStatus(key), value, key })); return <><PageHeader eyebrow="Trust & Safety / Overview" title="Trust & Safety" subtitle="Monitor reports, investigate marketplace issues, and protect TaskLocal customers and providers." action={<button className="button button-primary" onClick={() => goToReports()}><Filter size={16} /> View all reports</button>} /><div className="kpi-grid"><Kpi label="Open reports" value={metrics.open} note={`${metrics.total} total reports`} icon={BellRing} tone="teal" onClick={() => goToReports({ status: 'pending_review' })} /><Kpi label="Pending review" value={metrics.pending} note="Waiting for first action" icon={CircleHelp} tone="amber" onClick={() => goToReports({ status: 'pending_review' })} /><Kpi label="Investigating" value={metrics.investigating} note="Active case work" icon={Search} tone="blue" onClick={() => goToReports({ status: 'investigating' })} /><Kpi label="Safety concerns" value={metrics.safety} note="Reported safety issues" icon={AlertTriangle} tone="coral" onClick={() => goToReports({ type: 'safety_concern' })} /></div><div className="dashboard-grid"><Panel title="Reports by issue type" subtitle="All reported marketplace issues"><ReportTypeChart data={flagData} /></Panel><Panel title="Report status" subtitle="Current workflow state"><StatusChart data={statusData} /></Panel></div><section className="section-block"><div className="section-heading"><div><h2>Needs attention</h2><p>Dashboard prioritization based on report type and current status. This is not an official risk score.</p></div><button className="text-button" onClick={() => goToReports()}>Open reports <ChevronRight size={15} /></button></div><div className="attention-list">{attention.map((report) => <ReportRow key={report.report_id} report={report} openReport={openReport} />)}</div></section></> }
function Kpi({ label, value, note, icon: Icon, tone, onClick }) { return <button className={`kpi-card ${tone}`} onClick={onClick}><div className="kpi-top"><span>{label}</span><span className="kpi-icon"><Icon size={17} /></span></div><strong>{value}</strong><small>{note}</small></button> }
function Panel({ title, subtitle, children }) { return <section className="panel"><div className="panel-heading"><div><h2>{title}</h2><p>{subtitle}</p></div><button className="icon-button" aria-label="Chart options"><SlidersHorizontal size={17} /></button></div>{children}</section> }
function ReportTypeChart({ data }) { return <div className="chart-wrap"><ResponsiveContainer width="100%" height={240}><BarChart data={data} layout="vertical" margin={{ left: 12, right: 16 }}><CartesianGrid horizontal={false} stroke="#e6ecec" /><XAxis type="number" allowDecimals={false} axisLine={false} tickLine={false} /><YAxis type="category" dataKey="name" width={105} axisLine={false} tickLine={false} tick={{ fill: '#5f7072', fontSize: 12 }} /><Tooltip cursor={{ fill: '#f2f6f6' }} /><Bar dataKey="value" fill="#118a80" radius={[0, 5, 5, 0]} barSize={22} /></BarChart></ResponsiveContainer></div> }
function StatusChart({ data }) { const colors = ['#f0ad4e', '#4285a8', '#77a99b']; return <div className="status-chart"><ResponsiveContainer width="48%" height={190}><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius={56} outerRadius={78} paddingAngle={4}>{data.map((item, index) => <Cell key={item.key} fill={colors[index]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><div className="legend">{data.map((item, index) => <div key={item.key}><i style={{ background: colors[index] }} /><span>{item.name}</span><strong>{item.value}</strong></div>)}</div></div> }

function Reports({ data, metrics, globalSearch, openReport, initialFilters }) { const [filters, setFilters] = useState({ type: initialFilters.type || '', status: initialFilters.status || '', reference: '', service: '', attention: '' }); const [sort, setSort] = useState('priority'); const reports = useMemo(() => { const search = globalSearch.trim().toLowerCase(); return data.reports.filter((report) => !search || [report.report_id, report.reference_id, report.booking?.booking_id, report.listing?.listing_id, report.provider_id, report.customer?.customer_id].some((value) => value?.toLowerCase().includes(search))).filter((report) => !filters.type || report.flag_type === filters.type).filter((report) => !filters.status || report.flag_status === filters.status).filter((report) => !filters.reference || report.reference_type === filters.reference).filter((report) => !filters.service || report.service_type === filters.service).filter((report) => !filters.attention || report.attention.label === filters.attention).sort((a, b) => sort === 'priority' ? a.attention.rank - b.attention.rank : a.report_id.localeCompare(b.report_id)) }, [data.reports, filters, globalSearch, sort]); return <><PageHeader eyebrow="Trust & Safety / Reports" title="Reports" subtitle={`${reports.length} of ${metrics.total} reports in view.`} /><div className="filter-bar"><div className="filter-label"><Filter size={16} /> Filters</div><Select label="Issue type" value={filters.type} onChange={(value) => setFilters({ ...filters, type: value })} options={FLAG_LABELS} /><Select label="Status" value={filters.status} onChange={(value) => setFilters({ ...filters, status: value })} options={STATUS_LABELS} /><Select label="Reference" value={filters.reference} onChange={(value) => setFilters({ ...filters, reference: value })} options={{ listing_id: 'Listing', booking_id: 'Booking' }} /><Select label="Service" value={filters.service} onChange={(value) => setFilters({ ...filters, service: value })} options={SERVICE_LABELS} /><Select label="Attention" value={filters.attention} onChange={(value) => setFilters({ ...filters, attention: value })} options={{ 'High attention': 'High attention', 'Medium attention': 'Medium attention', 'Lower attention': 'Lower attention' }} /><button className="sort-button" onClick={() => setSort(sort === 'priority' ? 'id' : 'priority')}><SlidersHorizontal size={15} /> {sort === 'priority' ? 'Priority' : 'Report ID'}</button></div><div className="table-panel"><div className="table-scroll"><table><thead><tr><th>Report</th><th>Issue type</th><th>Status</th><th>Reference</th><th>Service</th><th>Customer</th><th>Provider</th><th>Rating</th><th>Attention</th><th /></tr></thead><tbody>{reports.map((report) => <ReportTableRow key={report.report_id} report={report} openReport={openReport} />)}</tbody></table></div>{!reports.length && <EmptyState title="No reports found" description="Try adjusting your filters or search terms." />}</div></> }
function Select({ label, value, onChange, options }) { return <label className="select-field"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}><option value="">All</option>{Object.entries(options).map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label> }
function ReportRow({ report, openReport }) { return <button className="attention-row" onClick={() => openReport(report)}><div className={`attention-mark ${report.attention.label.split(' ')[0].toLowerCase()}`} /><div className="attention-copy"><strong>{formatFlag(report.flag_type)}</strong><span>{report.report_id} · {report.reference_id}</span></div><StatusBadge value={report.flag_status} /><span className="row-arrow"><ChevronRight size={17} /></span></button> }
function ReportTableRow({ report, openReport }) { return <tr onClick={() => openReport(report)}><td><strong>{report.report_id}</strong><small>{report.reference_type === 'booking_id' ? 'Booking report' : 'Listing report'}</small></td><td><IssueBadge value={report.flag_type} /></td><td><StatusBadge value={report.flag_status} /></td><td><strong>{report.reference_id}</strong></td><td>{formatService(report.service_type)}</td><td>{report.customer?.customer_id || '—'}</td><td>{report.provider_id || '—'}</td><td>{report.rating ? `${report.rating}/5` : '—'}</td><td><span className={`attention-pill ${report.attention.label.split(' ')[0].toLowerCase()}`}>{report.attention.label}</span></td><td><ChevronRight size={16} className="muted-icon" /></td></tr> }
function StatusBadge({ value }) { return <span className={`status-badge ${value}`}>{formatStatus(value)}</span> }
function IssueBadge({ value }) { return <span className={`issue-badge ${value}`}><i />{formatFlag(value)}</span> }

function ReportDrawer({ report, onClose, onStatusChange }) { return <div className="drawer-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><aside className="detail-drawer"><div className="drawer-header"><div><div className="eyebrow">Report detail</div><h2>{report.report_id}</h2></div><button className="icon-button" onClick={onClose} aria-label="Close report detail"><X size={19} /></button></div><div className="drawer-content"><div className="detail-tags"><IssueBadge value={report.flag_type} /><StatusBadge value={report.flag_status} /></div><DetailSection title="Report information"><Detail label="Reference type" value={report.reference_type === 'booking_id' ? 'Booking' : 'Listing'} /><Detail label="Reference ID" value={report.reference_id} /><Detail label="Rating" value={report.rating ? `${report.rating} / 5` : 'Not applicable'} /><Detail label="Attention" value={`${report.attention.label} · dashboard prioritization`} /></DetailSection><DetailSection title="Related marketplace information">{report.booking ? <><Detail label="Booking ID" value={report.booking.booking_id} /><Detail label="Booking status" value={report.booking.booking_status} /><Detail label="Total cost" value={money(report.booking.total_cost)} /><Detail label="Customer ID" value={report.booking.customer_id} /><Detail label="Listing ID" value={report.booking.listing_id} /><Detail label="Provider ID" value={report.provider_id} /><Detail label="Service type" value={formatService(report.service_type)} /><Detail label="Listing title" value={report.listing?.title} /></> : report.listing ? <><Detail label="Listing ID" value={report.listing.listing_id} /><Detail label="Listing title" value={report.listing.title} /><Detail label="Provider ID" value={report.provider_id} /><Detail label="Service type" value={formatService(report.service_type)} /><Detail label="Description" value={report.listing.description} /><Detail label="Hourly rate" value={money(report.listing.hourly_rate)} /></> : <div className="missing-record"><AlertTriangle size={17} /><span>Related record unavailable</span></div>}</DetailSection><DetailSection title="Investigation action"><p className="neutral-note">This report reflects reported behavior and is not confirmation of wrongdoing.</p><div className="action-stack"><button className="button button-primary" onClick={() => onStatusChange('investigating')}>Mark as investigating</button><button className="button button-secondary" onClick={() => onStatusChange('resolved')}>Mark as resolved</button><button className="button button-ghost" onClick={() => onStatusChange('pending_review')}>Return to pending review</button></div></DetailSection></div></aside></div> }
function DetailSection({ title, children }) { return <section className="detail-section"><h3>{title}</h3>{children}</section> }
function Detail({ label, value }) { return <div className="detail-row"><span>{label}</span><strong>{value || '—'}</strong></div> }

function Listings({ data, openReport }) { const [search, setSearch] = useState(''); const listings = data.listings.filter((listing) => [listing.listing_id, listing.provider_id, listing.title, listing.service_type].some((value) => value.toLowerCase().includes(search.toLowerCase()))); return <><PageHeader eyebrow="Marketplace / Listings" title="Listings" subtitle="Review listings with associated Trust & Safety reports." action={<SearchInput value={search} onChange={setSearch} placeholder="Search listings" />} /><div className="entity-grid">{listings.map((listing) => <article className="entity-card" key={listing.listing_id}><div className="entity-card-top"><span className="service-icon"><Building2 size={17} /></span><span className="count-chip">{plural(listing.reports.length, 'report')}</span></div><h3>{listing.title}</h3><p>{listing.description}</p><div className="entity-meta"><span>{listing.listing_id}</span><span>{formatService(listing.service_type)}</span><strong>{money(listing.hourly_rate)} / hr</strong></div>{listing.reports.length > 0 && <div className="related-reports"><span>Related reports</span>{listing.reports.slice(0, 3).map((report) => <button key={report.report_id} onClick={() => openReport(report)}><IssueBadge value={report.flag_type} /><StatusBadge value={report.flag_status} /></button>)}</div>}</article>)}</div>{!listings.length && <EmptyState title="No listings found" description="Try a different listing ID, provider ID, or service." />}</> }
function Bookings({ data, openReport }) { const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [hasReport, setHasReport] = useState(''); const bookings = data.bookings.filter((booking) => [booking.booking_id, booking.customer_id, booking.listing_id, booking.provider_id].some((value) => value?.toLowerCase().includes(search.toLowerCase()))).filter((booking) => !status || booking.booking_status === status).filter((booking) => !hasReport || (hasReport === 'yes' ? booking.reports.length : !booking.reports.length)); return <><PageHeader eyebrow="Marketplace / Bookings" title="Bookings" subtitle="Trace customer bookings back to listings, providers, and reports." action={<SearchInput value={search} onChange={setSearch} placeholder="Search bookings" />} /><div className="filter-bar compact"><Select label="Booking status" value={status} onChange={setStatus} options={{ draft: 'Draft', pending: 'Pending', confirmed: 'Confirmed', completed: 'Completed' }} /><Select label="Has report" value={hasReport} onChange={setHasReport} options={{ yes: 'Has report', no: 'No report' }} /></div><div className="table-panel"><div className="table-scroll"><table><thead><tr><th>Booking</th><th>Customer</th><th>Listing / service</th><th>Provider</th><th>Status</th><th>Total</th><th>Reports</th></tr></thead><tbody>{bookings.map((booking) => <tr key={booking.booking_id}><td><strong>{booking.booking_id}</strong></td><td>{booking.customer_id}</td><td><strong>{booking.listing?.title || 'Listing unavailable'}</strong><small>{formatService(booking.listing?.service_type)}</small></td><td>{booking.provider_id || '—'}</td><td><span className={`booking-status ${booking.booking_status}`}>{booking.booking_status}</span></td><td>{money(booking.total_cost)}</td><td>{booking.reports.length ? <div className="inline-reports">{booking.reports.map((report) => <button key={report.report_id} onClick={() => openReport(report)}>{formatFlag(report.flag_type)}</button>)}</div> : '—'}</td></tr>)}</tbody></table></div>{!bookings.length && <EmptyState title="No bookings found" description="Try adjusting the search or filters." />}</div></> }
function Providers({ data }) { const [search, setSearch] = useState(''); const providers = getProviders(data).filter((provider) => provider.provider_id.toLowerCase().includes(search.toLowerCase())); return <><PageHeader eyebrow="Marketplace / Providers" title="Providers" subtitle="Provider-level patterns derived from listings and reports only." action={<SearchInput value={search} onChange={setSearch} placeholder="Search provider IDs" />} /><div className="table-panel"><div className="table-scroll"><table><thead><tr><th>Provider</th><th>Listings</th><th>Service types</th><th>Avg. hourly rate</th><th>Total reports</th><th>Safety</th><th>Pricing</th><th>Low rating</th><th>No-show</th></tr></thead><tbody>{providers.map((provider) => <tr key={provider.provider_id}><td><strong>{provider.provider_id}</strong></td><td>{provider.listings.length}</td><td>{provider.serviceTypes.map(formatService).join(', ')}</td><td>{money(provider.averageRate)}</td><td>{provider.reports.length}</td><td className="metric-alert">{provider.safetyConcerns}</td><td>{provider.pricingDisputes}</td><td>{provider.lowRatings}</td><td>{provider.noShows}</td></tr>)}</tbody></table></div></div></> }
function Customers({ data }) { const [search, setSearch] = useState(''); const customers = getCustomers(data).filter((customer) => customer.customer_id.toLowerCase().includes(search.toLowerCase())); return <><PageHeader eyebrow="Marketplace / Customers" title="Customers" subtitle="Customer activity connected to bookings and Trust & Safety reports." action={<SearchInput value={search} onChange={setSearch} placeholder="Search customer IDs" />} /><div className="table-panel"><div className="table-scroll"><table><thead><tr><th>Customer</th><th>Signup date</th><th>Bookings</th><th>Reports connected to bookings</th></tr></thead><tbody>{customers.map((customer) => <tr key={customer.customer_id}><td><strong>{customer.customer_id}</strong></td><td>{customer.signup_date}</td><td>{customer.bookingCount}</td><td>{customer.reportCount}</td></tr>)}</tbody></table></div></div></> }
function Analytics({ data, metrics }) { const serviceData = Object.entries(metrics.byService).map(([key, value]) => ({ name: formatService(key), value })); const providers = getProviders(data).sort((a, b) => b.reports.length - a.reports.length).slice(0, 8); return <><PageHeader eyebrow="Trust & Safety / Analytics" title="Analytics" subtitle="Patterns in reported marketplace activity, presented without unsupported conclusions." /><div className="dashboard-grid"><Panel title="Reports by service type" subtitle="Resolved relationships only"><div className="chart-wrap"><ResponsiveContainer width="100%" height={260}><BarChart data={serviceData} margin={{ left: 8, right: 14 }}><CartesianGrid vertical={false} stroke="#e6ecec" /><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: '#5f7072', fontSize: 12 }} /><YAxis allowDecimals={false} axisLine={false} tickLine={false} /><Tooltip /><Bar dataKey="value" fill="#3c789b" radius={[5, 5, 0, 0]} barSize={36} /></BarChart></ResponsiveContainer></div></Panel><Panel title="Providers by report volume" subtitle="Association with reports is not a finding of wrongdoing"><div className="provider-bars">{providers.map((provider) => <div className="provider-bar" key={provider.provider_id}><div><strong>{provider.provider_id}</strong><span>{plural(provider.reports.length, 'report')}</span></div><div className="bar-track"><i style={{ width: `${Math.max(8, provider.reports.length / (providers[0]?.reports.length || 1) * 100)}%` }} /></div></div>)}</div></Panel></div><section className="section-block analytics-note"><div className="note-icon"><ClipboardList size={18} /></div><div><h3>Data context</h3><p>{data.chatbotRequests.length} chatbot job requests are available as contextual request text. They are not used as evidence of safety issues.</p></div></section></> }
function SearchInput({ value, onChange, placeholder }) { return <div className="page-search"><Search size={16} /><input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /></div> }
function EmptyState({ title, description }) { return <div className="empty-state"><div className="empty-icon"><Search size={19} /></div><h3>{title}</h3><p>{description}</p></div> }
function LoginState({ onSignIn, error, useLocalAuth = false }) { const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [submitting, setSubmitting] = useState(false); const [formError, setFormError] = useState(''); const submit = async (event) => { event.preventDefault(); setFormError(''); setSubmitting(true); try { await onSignIn(email, password) } catch (signInError) { setFormError(signInError.message) } finally { setSubmitting(false) } }; return <main className="auth-shell"><div className="auth-panel"><div className="auth-brand"><span className="brand-mark"><ShieldCheck size={20} /></span><strong>tasklocal</strong></div><div className="eyebrow">Trust &amp; Safety</div><h1>Sign in to the safety workspace</h1><p>{useLocalAuth ? 'Use your local admin account to review marketplace reports.' : 'Use your individual safety team account to review marketplace reports.'}</p><form onSubmit={submit} className="auth-form"><label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" required /></label><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="current-password" required /></label>{(formError || error) && <div className="auth-error" role="alert">{formError || error}</div>}<button className="button button-primary" type="submit" disabled={submitting}>{submitting ? 'Signing in...' : 'Sign in'}</button></form></div></main> }
function AccessDeniedState({ onSignOut }) { return <main className="auth-shell"><div className="auth-panel"><div className="auth-brand"><span className="brand-mark"><ShieldCheck size={20} /></span><strong>tasklocal</strong></div><div className="eyebrow">Trust &amp; Safety</div><h1>Access not available</h1><p>This account is not assigned to the Trust &amp; Safety workspace.</p><button className="button button-secondary" onClick={() => onSignOut()}>Sign out</button></div></main> }
function LoadingState({ message = 'Loading Trust & Safety data' }) { return <div className="state-screen"><div className="loader" /><h2>{message}</h2><p>Connecting the marketplace records...</p></div> }
function ErrorState({ message, retry }) { return <div className="state-screen error-screen"><div className="empty-icon"><AlertTriangle size={22} /></div><h2>Unable to load Trust &amp; Safety data</h2><p>{message || 'The source files could not be loaded.'}</p><button className="button button-primary" onClick={retry}>Retry loading data</button></div> }

export default App